### ISSUE TITLE
syncing from orbitdb http api dev to in-browser not working

### ISSUE THREAD

**Issue by sloev** [orbitdb/orbit-db#825]
i have the following html in my browser:

```
<script src="https://unpkg.com/ipfs@0.33.1/dist/index.js"></script>
<script src="https://unpkg.com/orbit-db@0.19.9/dist/orbitdb.min.js"></script>

<pre id="pre"></pre>
<script>
  const ipfsConfig = {
    repo: "orbitdb/presence/" + Math.random(),
    start: true,
    EXPERIMENTAL: {
      pubsub: true
    },
    config: {
      Addresses: {
        Swarm: [
          // "/dns4/star-signal.cloud.ipfs.team/wss/p2p-webrtc-star"
          "/dns4/ws-star.discovery.libp2p.io/tcp/443/wss/p2p-websocket-star",
        //   "/dns4/wrtc-star.discovery.libp2p.io/tcp/443/wss/p2p-webrtc-star"
        ]
      }
    }
  };

  // Configuration for the database
  const dbConfig = {
      create:false,
    // Don't wait to load from the network
    sync: true,

  };

  const store = async name => {
    return new Promise((resolve, reject) => {
      const ipfs = new Ipfs(ipfsConfig);
      ipfs.on("error", e => console.error(e));
      ipfs.on("ready", async () => {
        console.log("ipfs is ready")
        try {
          const orbitdb = new OrbitDB(ipfs);
          const db = await orbitdb.eventlog(name, dbConfig);
          console.log("db is ready")
          resolve(db);
        } catch (e) {
          reject(e);
        }
      });
    });
  };
  (async () => {
    const db = await store("/orbitdb/zdpuAurMtsBdwy6WQuHJymGLGXGF9voY1mn8H22UX8yFWZeCP/landsat");
    const id = (await db._ipfs.id()).id;
    const address = db.address.toString();
    await db.load();
    db.events.on("replicate", ()=>console.log("replicate"))
    db.events.on("replicated", ()=>console.log("replicated"))
    setInterval(async () => {
      await db.load();
      data = await db.get("zdpuAypiQQQXLA8Kpj1zThyvsNaTbyVPpoc33ZAK6FUDYQhVg");
      console.log("data", data)
      document.getElementById("pre").innerHTML = JSON.stringify(
        {
            funk:"lol",
          address,
          id,
          data: await db.iterator({ limit: -1 }).collect().map((e) => e.payload.value),
          databasePeers: await db._ipfs.pubsub.peers(address),
          networkPeers: await db._ipfs.pubsub.peers(),
        },
        null,
        2
      );
    }, 3 * 1000);
  })();
</script>
```

i am running  `ipfs/go-ipfs:v0.4.22`  and `phillmac/orbit-db-http-api-dev:debug` locally using the following docker-compose script:

```
version: "3.7"

services:
  ipfs:
    image: ipfs/go-ipfs:v0.4.22
    restart: unless-stopped
    command: ["daemon", "--migrate=true", "--enable-gc", "--enable-namesys-pubsub"]
    volumes:
      - ./ipfs_data:/data/ipfs
    ports:
      - 0.0.0.0:4001:4001/tcp
      - 0.0.0.0:5001:5001/tcp
    networks:
      - ipfs
  orbitdb-api:
    image:  phillmac/orbit-db-http-api-dev:debug
    restart: unless-stopped
    command: ["src/cli.js", "api", "--debug"]
    init: TRUE
    environment:
      IPFS_HOST: 'ipfs'
      ORBITDB_DIR: '/orbitdb'
      FORCE_HTTP1: 'true'
      ANNOUNCE_DBS: 'true'
      LOG: 'DEBUG'
    depends_on:
      - ipfs
    ports:
      - 0.0.0.0:3000:3000/tcp
    networks:
      - ipfs
    volumes:
      - ./orbitdb-data:/orbitdb
networks:
  ipfs:
```

i have created a database:

```
curl 'http://localhost:3000/db/landsat' -d "create=true" -d "type=eventlog" -d "replicate=true"

{"address":{"root":"zdpuAurMtsBdwy6WQuHJymGLGXGF9voY1mn8H22UX8yFWZeCP","path":"landsat"},"dbname":"landsat","id":"/orbitdb/zdpuAurMtsBdwy6WQuHJymGLGXGF9voY1mn8H22UX8yFWZeCP/landsat","ready":true,"loaded":true,"oplog":{"length":5},"replicationQueue":{"buffer":[],"queue":{},"fetching":0},"options":{"create":"true","localOnly":false,"maxHistory":-1,"overwrite":true,"replicate":"true"},"canAppend":true,"type":"eventlog","indexLength":5,"accessController":{"type":"ipfs","write":["0315926fe75c6688957a04a915346f49c6b9f8cf1ba9586ba17d26e93950c18597"]},"replicationStatus":{"progress":5,"max":5,"buffered":0,"queued":0},"peers":[],"peerCount":0,"capabilities":["add","get","iterator"]}%  
```

and i have created an object:
```
curl -X POST http://localhost:3000/db/landsat/add -d 'hello world'                                  

{"hash":"zdpuAsNxhBHdq7TgxHPQ5Mtf5YcpW7XXSDUFFqqpb2MLpQsQC"}%   
```

but when i try to connect to my db from my browser html file i get the following error:

```
 (in promise) Error: 'options.create' set to 'false'. If you want to create a database, set 'options.create' to 'true'
```

which tells me the database does not exist as i am specifically telling orbitdb in browser to not create db if not exist.

# i just want to be able to tail an oplog from server to browser through ipfs
i thought i could:

* run local ipfs node
* run local orbitdb http api
* create db locally in orbitdb and put docs in it

* create in-browser ipfs and orbitdb 
* in-browser connect to already created db
* in-browser tail eventlog

but it seems impossible, i've tried for a few days now
